# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx4G
#org.gradle.parallel=true
org.gradle.caching=false
org.gradle.caching.debug=false
org.gradle.parallel=false
#org.gradle.configureondemand=true

# Mod properties
mod.version=3.0.0
mod.group=com.quantumgarbage
mod.id=screenshotsettings
mod.name=Screenshot Settings

# Used for the mod metadata
mod.mc_dep_fabric=[VERSIONED]
mod.mc_dep_forgelike=[VERSIONED]
# Used for the release title. I.e. '1.20.x'
mod.mc_title=[VERSIONED]
# Space separated versions for publishing. I.e. '1.20, 1.20.1'
mod.mc_targets=[VERSIONED]

# Mod setup
deps.mixin_extras=0.4.1
deps.fabric_loader=0.16.10
deps.fabric_version=[VERSIONED]

deps.forge_loader=[VERSIONED]
deps.neoforge_loader=[VERSIONED]
deps.neoforge_patch=[VERSIONED]

# Mod dependencies
deps.yarn_build=[VERSIONED]
deps.architectury_api=[VERSIONED]
deps.modmenu_version=[VERSIONED]
deps.yacl_version=[VERSIONED]
deps.cloth_version=[VERSIONED]
deps.iris_version=[VERSIONED]
deps.sodium_version=[VERSIONED]

# Publishing
publish.modrinth="M0QvZmyL"
publish.curseforge="720608"