modLoader = "javafml"
loaderVersion = "*"
license = "Apache-2.0"
issueTrackerURL="https://github.com/fmbellomy/ScreenshotSettings/issues"

[[mods]]
modId = "screenshotsettings"
version = "${version}"
displayName = "${name}"
authors = "esoterica"
description = ""
logoFile = "assets/screenshotsettings/icon.png"
logoBlur = false

[[mixins]]
config = "template-common.mixins.json"

[[mixins]]
config = "template-neoforge.mixins.json"