mod.mc_dep_fabric==1.20.1
mod.mc_dep_forgelike=[1.20, 1.20.1]
mod.mc_title=1.20.1
mod.mc_targets=1.20.1

deps.forge_loader=47.3.0
deps.neoforge_loader=[UNSUPPORTED]

deps.yarn_build=10
deps.fabric_version=0.92.3+1.20.1
deps.modmenu_version=7.2.2

deps.architectury_api=9.2.14
deps.yacl_version=3.6.6+1.20.1-fabric
deps.cloth_version=11.1.136
deps.iris_version=1.7.6+1.20.1
deps.sodium_version=mc1.20.1-0.5.13-fabric

loom.platform=fabric
