# Automatically build the project and run any configured tests for every push
# and submitted pull request. This can help catch issues that only occur on
# certain platforms or Java versions, and provides a first line of defence
# against bad commits.

name: build
on: [pull_request, push]

jobs:
  build:
    runs-on: 'ubuntu-latest'
    steps:
      - name: checkout repository
        uses: actions/checkout@v5
      - name: validate gradle wrapper
        uses: gradle/actions/wrapper-validation@v5
      - name: setup jdk ${{ matrix.java }}
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'microsoft'
          cache: 'gradle'
      - name: make gradle wrapper executable
        run: chmod +x ./gradlew
      - name: set 1.20.1-fabric
        run: ./gradlew "Set active project to 1.20.1-fabric"
      - name: build 1.20.1-fabric
        run: ./gradlew :1.20.1-fabric:build

      - name: set 1.21.1-fabric
        run: ./gradlew "Set active project to 1.21.1-fabric"
      - name: build 1.21.1-fabric
        run: ./gradlew :1.21.1-fabric:build

      - name: set 1.21.1-neoforge
        run: ./gradlew "Set active project to 1.21.1-neoforge"
      - name: build 1.21.1-neoforge
        run: ./gradlew :1.21.1-neoforge:build

      - name: publish fabric 1.20.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: M0QvZmyL
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 720608
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            versions/1.20.1-fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            versions/1.20.1-fabric/build/libs/*-@(dev|sources|javadoc).jar
          version-type: release
          loaders:
            fabric
          game-versions: |
            1.20.1
      - name: publish fabric 1.21.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: M0QvZmyL
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 720608
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            versions/1.21.1-fabric/build/libs/!(*-@(dev|sources|javadoc)).jar
            versions/1.21.1-fabric/build/libs/*-@(dev|sources|javadoc).jar
          version-type: release
          loaders:
            fabric
          game-versions: |
            [1.21,1.21.1]
      - name: publish neoforge 1.21.1
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}
          modrinth-id: M0QvZmyL
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 720608
          github-token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            versions/1.21.1-neoforge/build/libs/!(*-@(dev|sources|javadoc)).jar
            versions/1.21.1-neoforge/build/libs/*-@(dev|sources|javadoc).jar
          version-type: release
          loaders:
            neoforge
          game-versions: |
            [1.21,1.21.1]

      - name: capture build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Artifacts
          path:
            versions/1.20.1-fabric/build/libs/
            versions/1.21.1-fabric/build/libs/
            versions/1.21.1-neoforge/build/libs/



