name: mc-publish

on:
  push:
    branches: [ mistress ]
  pull_request:
    branches: [ mistress ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      -   uses: actions/checkout@v2
      -   name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            distribution: 'temurin'
            java-version: 17
      -   name: Grant execute permission for gradlew
          run: chmod +x gradlew
          # I seriously shouldn't have to do this, but I'm at a loss with these failed GH actions at this point.
      -   name: Generate Gradle Wrapper
          run: gradle wrapper --gradle-version 7.4
      -   name: Build with Gradle
          run: ./gradlew build

      - name: Publish to MR and GH
        uses: Kir-Antipov/mc-publish@v3.2
        with:
          game-versions: 1.19.2
          modrinth-dependencies: |
            yacl | depends 
            modmenu | depends
            fabric-api | depends
            iris | suggests
          modrinth-id: M0QvZmyL
          modrinth-token: ${{ secrets.MODRINTH_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}